### ISSUE TITLE
Do we still need "playlist_started" variable?

### ISSUE THREAD

**Issue by eichblatt** [eichblatt/litestream#118]
I'm not sure what this variable does any more. Maybe we can delete it.

**Comment by ma261065** [comment]
This is used in two places:

1) To show the "Playlist Not Started" message in the debug output.

```
Playing -- Read 2589932/2991345 (87%) of track 8/8 InBuffer: 100% OutBuffer: 93%
Playing -- Read 2718685/2991345 (91%) of track 8/8 InBuffer: 100% OutBuffer: 99%
Playing -- Read 2848915/2991345 (95%) of track 8/8 InBuffer: 100% OutBuffer: 99%
Playing -- Read 2977780/2991345 (100%) of track 8/8 InBuffer: 100% OutBuffer: 100%
Track read end
Finished reading playlist
Playlist not started
Track 8 decode end
Finished decoding playlist
Track play end
Finished playing playlist
Playlist not started
Playlist not started
Playlist not started
Playlist not started
Playlist not started
Playlist not started
```

2) In update_display() to show the "Play", "Pause" & "Stop" icons

```
def update_display(player):
    # display_tracks(*player.track_names())
    tm.clear_bbox(tm.playpause_bbox)
    if not player.is_started():
        pass
    elif player.is_stopped():
        tm.tft.fill_polygon(tm.StopPoly, tm.playpause_bbox.x0, tm.playpause_bbox.y0, play_color)
    elif player.is_playing():
        tm.tft.fill_polygon(tm.PlayPoly, tm.playpause_bbox.x0, tm.playpause_bbox.y0, play_color)
    elif player.is_paused():
        tm.tft.fill_polygon(tm.PausePoly, tm.playpause_bbox.x0, tm.playpause_bbox.y0, st7789.WHITE)
```

It is set to ```true``` in```read_http_header()```  and back to ```false``` in ```handle_end_of_track_read()``` and also set to ```false``` in ```decode_chunk()``` when we finish decoding the playlist.

I think that the debug output case can simply be replaced with ``` if self.PLAY_STATE == play_state_Stopped```

For the second case ```handle_end_of_track_read()``` will always be called just before ```decode_chunk()``` finishes decoding the playlist, so setting it to ```false``` again in ```decode_chunk()``` seems superfluous.

Note that the audio will still be playing for a few seconds after ```handle_end_of_track_read()```, so I wonder the current behaviour in ```update_display()``` was even intended?

Would it be possible to update the logic in ```update_display()``` to use the existing player_state variables?

The justification for this change is that our logic for play/pause/stop/rewind is quite convoluted (and can probably be simplified), and this introduces yet another variable and complexity to managing the player state.

**Comment by ma261065** [comment]
![image](https://github.com/eichblatt/litestream/assets/7016239/89188919-3f30-4ae2-8d9a-71f9ddedf97d)

**Comment by eichblatt** [comment]
I will look into removing the superfluous setting of is_started to false in decode_chunk().

For the display of the play_state icon, there are currently 4 play_state icons:
- show is playing (triangle)
- show is paused (2 verticals)
- show is stopped (square)
- show has completed (empty)
 
Note that if the "autoplay" option were false (which is no longer an an option), the show would not start playing immediately upon selection. In that case, we would see the empty icon before we pressed "play/pause". However, with autostart being true, we only ever see the empty icon after a show has completed. 

I like the visual indication that the show has completed successfully, but we could use "stopped" state when the show is finished, and eliminate the "show is stopped" square icon altogether. We can indicate both "stopped" and "completed" with the empty icon (which I kind of like, less busy).
