### ISSUE TITLE
Enhancement: Allow re-scan on WiFi list

### ISSUE THREAD

**Issue by ma261065** [eichblatt/litestream#170]
If your WiFi is down then it won't show in the list. If it then comes back up again the list doesn't refresh, and you have to power cycle the device and go through the knob calibration process before you can see it.

It would be better to have a <Rescan> option in the WiFi list to refresh the available access points.

**Comment by eichblatt** [comment]
I will try to add this, as it was done in the Raspberry Pi model, with a message saying "press rewind to refresh list" or something.
