### ISSUE TITLE
Wrapping on config menu

### ISSUE THREAD

**Issue by ma261065** [eichblatt/litestream#171]
In the Config Menu you can scroll beyond the end of the list (i.e. past "Dev Mode") and it takes you back to the first item in the list ("Artists"). But you can't scroll any further down from there.

Either make the list endless (i.e. scrolling off the bottom takes you to the top and you can just keep scrolling), or make the list bounded so that you can't scroll past the bottom.

**Comment by eichblatt** [comment]
Will take a look this weekend
