### ISSUE TITLE
78 RPM Mode -- Too Many Failures

### ISSUE THREAD

**Issue by eichblatt** [eichblatt/litestream#192]
Here is an example of the playback error that happens pretty regularly in 78 RPM mode.

This may be due to the way that the program depends on the .m3u file, which isn't always available, but I'm not sure.

Example

```
in display_artist Dave Cavanaugh's Music,
Dave Cavanaugh's
  Music at 0,75
Track 4 decode start
ID3 tag size: 69799
Skipping 69799 bytes
Decoder Start success. Sync word at 0
Track play end
Track play start
Track read end
Track read start
Getting /download/78_are-my-ears-on-straight_gayla-peevey-norman-leyden-mel-leven_gbia0029051b/Are%20My%20Ears%20on%20Straight?%20-%20Gayla%20Peevey%20-%20Norman%20Leyden.mp3 from archive.org, Port:80, Offset 0
Redirecting to /14/items/78_are-my-ears-on-straight_gayla-peevey-norman-leyden-mel-leven_gbia0029051b/Are%20My%20Ears%20on%20Straight?%20-%20Gayla%20Peevey%20-%20Norman%20Leyden.mp3 from ia800104.us.archive.org, Port:80, Offset 0
Bad URL: http://archive.org/download/78_are-my-ears-on-straight_gayla-peevey-norman-leyden-mel-leven_gbia0029051b/Are%20My%20Ears%20on%20Straight?%20-%20Gayla%20Peevey%20-%20Norman%20Leyden.mp3
Headers: b'HTTP/1.1 404 Not Found\r\nServer: nginx/1.24.0 (Ubuntu)\r\nDate: Fri, 12 Jul 2024 13:02:36 GMT\r\nContent-Type: text/html; charset=UTF-8\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nSet-Cookie: donation-identifier=a81b2a4d11a23ad8747fa4becb2b558e; expires=Sat, 12-Jul-2025 13:02:36 GMT; Max-Age=31536000; path=/; domain=.archive.org\r\nSet-Cookie: abtest-identifier=d11546c88c93af04e9a97a9b9dba3545; expires=Sat, 12-Jul-2025 13:02:36 GMT; Max-Age=31536000; path=/; domain=.archive.org\r\nSet-Cookie: PHPSESSID=im2lahevs5oj0548ho6c3tbjg2; path=/; domain=.archive.org\r\nExpires: Thu, 19 Nov 1981 08:52:00 GMT\r\nCache-Control: no-store, no-cache, must-revalidate\r\nPragma: no-cache\r\nStrict-Transport-Security: max-age=15724800\r\n\r\n'
TrackLength: 0
Track read end
Finished reading playlist
writing json to /metadata/78rpm/1950_1960_tracknum.json
Error in playback loop list index out of range
```

**Comment by ma261065** [comment]
It may be to do with the .m3u, but fundamentally the track doesn't exist.

If I go to a browser and try and play [https://archive.org/download/78_are-my-ears-on-straight_gayla-peevey-norman-leyden-mel-leven_gbia0029051b/Are%20My%20Ears%20on%20Straight?%20-%20Gayla%20Peevey%20-%20Norman%20Leyden.mp3](https://archive.org/download/78_are-my-ears-on-straight_gayla-peevey-norman-leyden-mel-leven_gbia0029051b/Are%20My%20Ears%20on%20Straight?%20-%20Gayla%20Peevey%20-%20Norman%20Leyden.mp3)

I get:

**Page not found**
We’re sorry, the page you have requested is not available.

It is a bit weird that there is a '?' in the URL, as this usually indicates a URL parameter. Maybe they didn't take into account that song titles that pose a question would be translated to an invalid URL.

**Comment by eichblatt** [comment]
Maybe I need to escape the `?`

**Comment by ma261065** [comment]
I think it's a problem at their end. You can play around with escaping it until you can get it to play in a browser, but I'm not confident it will work.

**Comment by eichblatt** [comment]
The problem is that it's very hard to test. The way the program currently works, I have to wait until I stumble across a track with a strange character in the name.

I am pretty sure that the escaping will fix it, though. It certainly can't work _unless_ the characters are escaped, so escaping seems like the right thing.

But I am not sure that weird characters are my problem. Right now, all I know is that the 78RPM mode crashes too often.
