### ISSUE TITLE
I2S Driver Error

### ISSUE THREAD

**Issue by eichblatt** [eichblatt/litestream#43]
I am seeing this error

(154780) i2s(legacy): i2s_driver_uninstall(1493): I2S port 0 has not installed

when fast forwarding to a new song, right before it starts playing. It doesn't crash, or fail otherwise, but I don't think this error could be a good thing, so it may be a bad thing.

**Comment by ma261065** [comment]
Closed by https://github.com/eichblatt/litestream/pull/52/commits/8280e90053da48158e471f24f689453c849c4de6

We were using I2S "wrong". An I2S init does a de-init under the covers, so the error was because it was de-initting an already de-initted I2S device. Fix is to only do inits, never de-init.
