### ISSUE TITLE
Unplayable file

### ISSUE THREAD

**Issue by ma261065** [eichblatt/litestream#54]
https://archive.org/download/gd1982-04-11.sbd.miller.108852.flac16/gd82-04-11d1t02.ogg is unplayable.

Looks like it (again) doesn't quite meet the ogg spec.

**Comment by eichblatt** [comment]
Another one 

https://archive.org/download/gd1978-08-30.s2.sbd.miller.110151.flac16/gd78-08-30d3t03.ogg

**Comment by eichblatt** [comment]
The latest merge #63 fixed these issues
