### ISSUE TITLE
Error in playback loop unsupported types for __lt__: 'NoneType', 'float'

### ISSUE THREAD

**Issue by eichblatt** [eichblatt/litestream#95]
v1.0.5

When attempting to play track 3 (The Shape I'm In) from TheLastWaltzEnsemble 2/22/08, this error was thrown.

The error is thrown immediately when trying to decode the song.

The URL it is trying to play is https://archive.org/download/lwe2008-02-22.peluso.flac16/lwe2008-02-22mtxd1t03.mp3

```
Track read start
Track 2 decode start
ID3 tag size: 128527
Skipping 32150 bytes
Error in playback loop unsupported types for __lt__: 'NoneType', 'float'
```

**Comment by eichblatt** [comment]
The previous commit solves the error message that we initially saw (unsupported types for __lt__: 'NoneType', 'float'), but now we get a Decode Packet Failed error on the same track.

**Comment by ma261065** [comment]
Seems similar to this: https://forum.micropython.org/viewtopic.php?t=11653

**Comment by eichblatt** [comment]
Note: We see the same problem on this track: 
  https://archive.org/download/lwe2019-11-22.matrix.flac16/lastwaltz2019-11-22s2t01.mp3

**Comment by eichblatt** [comment]
> Seems similar to this: https://forum.micropython.org/viewtopic.php?t=11653 & [pycom/pycom-micropython-sigfox#584](https://github.com/pycom/pycom-micropython-sigfox/issues/584)

I don't think this is related. The initial error was due to a bug where the decode_chunk function, in some code branches, would return without an argument instead of returning an integer. The calling function expected an integer, compared it to another number and threw this exception.

That problem is fixed, but now the track runs into a Decode Packet failure. Probably because some part of my fix was wrong.

**Comment by eichblatt** [comment]
Fixed!!
